server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customerService
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: addressService
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/addresses/**
        - id: webUIService
          uri: lb://WEB-UI-SERVICE
          predicates:
            - Path=/, /home, /index, /**.js

